# Étape 1 : Construire l'application
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

# Copier le fichier pom.xml et les sources
COPY pom.xml .
COPY src ./src

# Exécuter Maven pour compiler et packager l'application
RUN mvn clean package -DskipTests

# Étape 2 : Construire l'image finale
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copier l'artefact JAR depuis l'étape de construction
COPY --from=build /app/target/*.jar app.jar

# Exposer le port utilisé par l'application
EXPOSE 8080

# Lancer l'application
ENTRYPOINT ["java", "-jar", "app.jar"]
